AKT.actionscripts.add_source_and_statement = {
meta:{label:'add_source_and_statement'},
actions:[
    {
        "element_id": "menus",
        "selector": "#menu_file > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "First, click on the File menu",
        "datetime": "Fri Oct 31 2025 21:40:49 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_file_newkb > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the New menu item to create a new KB.",
        "datetime": "Fri Oct 31 2025 21:40:52 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "myprompt",
        "selector": "[local_id=\"button_ok\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "value",
        "event_type": "click",
        "upper_selector": "#myprompt",
        "local_selector": "[local_id=\"button_ok\"]",
        "speech": "Click on the OK button.  You should see the metadata panel.",
        "datetime": "Fri Oct 31 2025 21:40:56 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "metadata_1",
        "selector": "[local_id=\"textarea_title\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "This is a new KB",
        "upper_selector": "#metadata_1",
        "local_selector": "[local_id=\"button_close\"]",
        "speech": "Enter a title for the KB in the title field",
        "datetime": "Fri Oct 31 2025 21:41:42 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "metadata_1",
        "selector": "[local_id=\"button_update\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "🞫",
        "event_type": "click",
        "upper_selector": "#metadata_1",
        "local_selector": "[local_id=\"button_close\"]",
        "speech": "Click on the Update button",
        "datetime": "Fri Oct 31 2025 21:41:42 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "metadata_1",
        "selector": "[local_id=\"button_close\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "🞫",
        "event_type": "click",
        "upper_selector": "#metadata_1",
        "local_selector": "[local_id=\"button_close\"]",
        "speech": "Click on the 🞫 button to close the metadata panel",
        "datetime": "Fri Oct 31 2025 21:41:42 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_kb > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the KB menu",
        "datetime": "Fri Oct 31 2025 21:41:53 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_kb_sources > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the Sources command",
        "datetime": "Fri Oct 31 2025 21:41:55 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_collection_1",
        "selector": "[local_id=\"button_new\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "New",
        "event_type": "click",
        "upper_selector": "#source_collection_1",
        "local_selector": "[local_id=\"button_new\"]",
        "speech": "Click on the New button to enter a new source",
        "datetime": "Fri Oct 31 2025 21:42:01 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_details_1",
        "selector": "[local_id=\"input_id\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "fred",
        "upper_selector": "#source_details_1",
        "local_selector": "[local_id=\"input_name\"]",
        "speech": "Enter an ID for this source",
        "datetime": "Fri Oct 31 2025 21:42:22 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_details_1",
        "selector": "[local_id=\"input_name\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "Freddy",
        "upper_selector": "#source_details_1",
        "local_selector": "[local_id=\"input_year\"]",
        "speech": "Enter the source's name",
        "datetime": "Fri Oct 31 2025 21:42:31 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_details_1",
        "selector": "[local_id=\"input_year\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "2025",
        "upper_selector": "#source_details_1",
        "local_selector": "[local_id=\"button_update\"]",
        "speech": "Enter the year when the source was interviewed",
        "datetime": "Fri Oct 31 2025 21:42:40 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_details_1",
        "selector": "[local_id=\"button_update\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "Update",
        "event_type": "click",
        "upper_selector": "#source_details_1",
        "local_selector": "[local_id=\"button_update\"]",
        "speech": "Click on the Update button",
        "datetime": "Fri Oct 31 2025 21:42:40 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_kb > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the KB menu",
        "datetime": "Fri Oct 31 2025 21:42:49 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_kb_statements > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the statements command",
        "datetime": "Fri Oct 31 2025 21:42:52 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_collection_1",
        "selector": "[local_id=\"button_new\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "New",
        "event_type": "click",
        "upper_selector": "#statement_collection_1",
        "local_selector": "[local_id=\"button_new\"]",
        "speech": "Click on the New button",
        "datetime": "Fri Oct 31 2025 21:42:56 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_details_1",
        "selector": "[local_id=\"textarea_formal\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "att_value(pine,height,tall)",
        "upper_selector": "#statement_details_1",
        "local_selector": "[local_id=\"button_add_source\"]",
        "speech": "Entter the statement att_value(pine,height,tall)",
        "datetime": "Fri Oct 31 2025 21:43:22 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_details_1",
        "selector": "[local_id=\"button_add_source\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "Add source",
        "event_type": "click",
        "upper_selector": "#statement_details_1",
        "local_selector": "[local_id=\"button_add_source\"]",
        "speech": "Click on the Add source button",
        "datetime": "Fri Oct 31 2025 21:43:22 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "source_collection_2",
        "element_type": "input",
        "selector": "[local_id=\"checkbox_fred\"]",
        "type": "checkbox",
        "event_type": "click",
        "input_type": "checkbox",
        "message": "Clicked on checkbox",
        "before": "next_action",
        "prompt": "Click on a button",
        "value": true,
        "upper_selector": "#source_collection_2",
        "local_selector": "[local_id=\"checkbox_fred\"]",
        "speech": "Click the checkbox for the source with ID fred",
        "datetime": "Fri Oct 31 2025 21:43:26 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_details_1",
        "selector": "[local_id=\"button_update\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "Update",
        "event_type": "click",
        "upper_selector": "#statement_details_1",
        "local_selector": "[local_id=\"button_update\"]",
        "speech": "Click on the Update button in the statement details panel",
        "datetime": "Fri Oct 31 2025 21:43:34 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_collection_1",
        "selector": "[local_id=\"statement_collection_1\"]",
        "type": "end_drag",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": {
            "x": 483,
            "y": 124
        },
        "event_type": "end_drag",
        "upper_selector": "#statement_collection_1",
        "local_selector": "[local_id=\"statement_collection_1\"]",
        "speech": "Drag the panel labelled statement_collection_1 by dragging its titlebar",
        "datetime": "Fri Oct 31 2025 21:43:41 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "statement_collection_1",
        "selector": "#statement_collection_1",
        "type": "click",
        "message": "Clicked on a panel",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click anywhere in the panel statement_collection_1",
        "value": null,
        "event_type": "click",
        "upper_selector": "#statement_collection_1",
        "local_selector": null,
        "speech": "Click anywhere in the panel labelled statement_collection_1",
        "datetime": "Fri Oct 31 2025 21:43:41 GMT+0000 (Greenwich Mean Time)"
    }
]};