AKT.actionscripts.formal_term = {
meta:{label:'formal_term'},
actions:[
    {
        "element_id": "menus",
        "selector": "#menu_kb > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the menu menu_kb",
        "datetime": "Mon Nov 03 2025 23:25:07 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "menus",
        "selector": "#menu_kb_formalterms > a",
        "type": "click",
        "message": "Clicked on a menu item",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a menu item",
        "value": "none",
        "speech": "Click on the menu menu_kb_formalterms",
        "datetime": "Mon Nov 03 2025 23:25:10 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_collection_1",
        "selector": "[local_id=\"button_new\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "New",
        "event_type": "click",
        "upper_selector": "#formal_term_collection_1",
        "local_selector": "[local_id=\"button_new\"]",
        "speech": "Click on the New button",
        "datetime": "Mon Nov 03 2025 23:25:12 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "#formal_term_details_1",
        "type": "click",
        "message": "Clicked on a panel",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click anywhere in the panel formal_term_details_1",
        "value": null,
        "event_type": "click",
        "upper_selector": "#formal_term_details_1",
        "local_selector": null,
        "speech": "Click anywhere in the panel labelled formal_term_details_1",
        "datetime": "Mon Nov 03 2025 23:25:15 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "[local_id=\"input_id\"]",
        "type": "input",
        "message": "Clicked on a key",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a key",
        "value": "spruce",
        "upper_selector": "#formal_term_details_1",
        "local_selector": "[local_id=\"select_formal_term_type\"]",
        "datetime": "Mon Nov 03 2025 23:25:22 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "#formal_term_details_1",
        "type": "click",
        "message": "Clicked on a panel",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click anywhere in the panel formal_term_details_1",
        "value": null,
        "event_type": "click",
        "upper_selector": "#formal_term_details_1",
        "local_selector": null,
        "speech": "Click anywhere in the panel labelled formal_term_details_1",
        "datetime": "Mon Nov 03 2025 23:25:22 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "[local_id=\"select_formal_term_type\"]",
        "type": "change",
        "message": "Changed the selected option in a select element",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Choose an option",
        "value": "object",
        "upper_selector": "#formal_term_details_1",
        "local_selector": "[local_id=\"select_formal_term_type\"]",
        "datetime": "Mon Nov 03 2025 23:25:24 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "#formal_term_details_1",
        "type": "click",
        "message": "Clicked on a panel",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click anywhere in the panel formal_term_details_1",
        "value": null,
        "event_type": "click",
        "upper_selector": "#formal_term_details_1",
        "local_selector": null,
        "speech": "Click anywhere in the panel labelled formal_term_details_1",
        "datetime": "Mon Nov 03 2025 23:25:24 GMT+0000 (Greenwich Mean Time)"
    },
    {
        "element_id": "formal_term_details_1",
        "selector": "[local_id=\"button_update\"]",
        "type": "click",
        "message": "Clicked on a button",
        "before": "previous_action",
        "after": "next_action",
        "prompt": "Click on a button",
        "value": "Update",
        "event_type": "click",
        "upper_selector": "#formal_term_details_1",
        "local_selector": "[local_id=\"button_update\"]",
        "speech": "Click on the Update button",
        "datetime": "Mon Nov 03 2025 23:25:27 GMT+0000 (Greenwich Mean Time)"
    }
]};